### PR TITLE
WIP: Jooq Graal test

### PR DESCRIPTION
**Pull request by morki**
I prepared Jooq test application based on your master_h2 branch.
It's working and compiles to native-image, but I have some issues.

1. `@TypeHint` from `micronaut-jooq` is not applied, so I had to copy it (and extend, PR will be in a minute to `micronaut-jooq`) to this application. This part:

```java
@TypeHint({
        LocalDate[].class,
        LocalDateTime[].class,
        LocalTime[].class,
        ZonedDateTime[].class,
        OffsetDateTime[].class,
        OffsetTime[].class,
        Instant[].class,
        Timestamp[].class,
        Date[].class,
        Time[].class,
        BigInteger[].class,
        BigDecimal[].class,
        UNumber[].class,
        UByte[].class,
        UInteger[].class,
        ULong[].class,
        Unsigned[].class,
        UShort[].class,
        Byte[].class,
        Integer[].class,
        Long[].class,
        Float[].class,
        Double[].class,
        String[].class,
        YearToMonth[].class,
        YearToSecond[].class,
        DayToSecond[].class,
        RowId[].class,
        Result[].class,
        Record[].class,
        JSON[].class,
        JSONB[].class,
        UUID[].class,
        byte[].class
})
```

2. I don't think using `--initialize-at-run-time=io.micronaut.configuration.jooq.spring.JooqExceptionTranslator` is the best choice.
The same for `--initialize-at-run-time=io.micronaut.configuration.jooq.spring.SpringTransactionProvider` from `micronaut-graal`.
I think somethink like `@AutomaticFeature` can resolve it, if yout don't have Spring on your classpath.

### CODE REVIEW

**Comment by ilopmar** [comment]
That was fast, thank you very much! I'll probably move this to another different repo, but as a starting point is good.

I'm working on another task so please give me some days to review it. I'll let you know if I have any problems.

Thanks again!

**Comment by morki** [comment]
@ilopmar of course, i just want to start at some point and PR in this project from your branch was the easies one for me :) 

Here is PR in micronaut SQL to add that all missing types, https://github.com/micronaut-projects/micronaut-sql/pull/182 just for reference. 

OT: I wish that another task is "flyway graalvm support" :rofl:

**Comment by ilopmar** [comment]
> OT: I wish that another task is "flyway graalvm support" :rofl: 

Yeah!

image


image

**Comment by morki** [comment]
@ilopmar I added usage of SimpleFlatMapper, which is very common as companion for JOOQ mapping (supports one to one, one to many etc.) and it seems it works well in native-image.

https://arnaudroger.github.io/blog/2017/02/27/jooq-one-to-many.html

**Comment by ilopmar** [comment]
@morki I've created a new repository for the JOOQ test application with the commits you submitted in this PR. I've also updated the build, dependencies and cleanup everything a little bit. You can take a look here: https://github.com/micronaut-graal-tests/micronaut-jooq-graal

> 1.- `@TypeHint` from micronaut-jooq is not applied, so I had to copy it (and extend, PR will be in a minute to micronaut-jooq) to this application.

The fix is already included in the latest version of micronaut-sql so no need for this anymore.

>2.-  I don't think using --initialize-at-run-time=io.micronaut.configuration.jooq.spring.JooqExceptionTranslator is the best choice.
The same for --initialize-at-run-time=io.micronaut.configuration.jooq.spring.SpringTransactionProvider from micronaut-graal.
I think somethink like `@AutomaticFeature` can resolve it, if yout don't have Spring on your classpath.

I don't think this is an issue. I see it as a warning because some Spring classes are not available. We use this in other places in Micronaut and I haven't seen a problem.

What I'm most worried about is the fact that we need to use `--report-unsupported-elements-at-runtime`. The usage of this flag is discouraged by the Graal team. I'll report an issue on their issue tracker.

A couple of additional questions because I don't have experience with Jooq

It is necessary to add a `@TypeHint` with all the Jooq record classes, like this:
```
@TypeHint(
        value = {PetRecord.class, OwnerRecord.class},
        accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS
)
```

Do all those classes have something in common? I see that at the end all implement `org.jooq.Record` interface. Is this a correct assumption? I was thinking on how we can automate the declaration of all those classes if we can find them somehow.


I see that you added the schema creation in both `application.yml` and `build.gradle`:
- https://github.com/micronaut-graal-tests/micronaut-jooq-graal/blob/master/src/main/resources/application.yml#L9
- https://github.com/micronaut-graal-tests/micronaut-jooq-graal/blob/master/build.gradle#L94

Can you explain why is it necessary? I assume that in a real project you would use Flyway or Liquibase to manage the db schema, so how that fits with Jooq?

**Comment by ilopmar** [comment]
@morki With this change https://github.com/micronaut-graal-tests/micronaut-jooq-graal/commit/d45e55ef9e41efbba973a1f6c8a05b1f1f187dd0 Jooq annotates the generated classes with `@Entity` so one of the existing Micronaut annotation mappers detects them and automatically mark them as `@Introspected`, so the reflect configuration is generated :)

**Comment by morki** [comment]
Hi @ilopmar, you are my hero, really! :) The simple trick with `@Entity` annotation is excelent, I will try it right now!

Edited: It works perfectly! :)

> Can you explain why is it necessary? I assume that in a real project you would use Flyway or Liquibase to manage the db schema, so how that fits with Jooq?

JOOQ classes are generated at build-time from schema, so in real project I use Flyway Gradle plugin and make JOOQ generation task depend on the Flyway migrate task, so new schema is available for the JOOQ generator.

I didn't want to introduce dependency on Flyway or other migration library in this PR to make it simple and focused on what it does, but for databases other than H2, we will probably need it anyway, so maybe we could add it.

> What I'm most worried about is the fact that we need to use --report-unsupported-elements-at-runtime. The usage of this flag is discouraged by the Graal team. I'll report an issue on their issue tracker.

I think this is only needed with usage of SimpleFlatMapper and H2. For H2, I don't know the reason, I only copied this from original code, where it was. For SimpleFlatMapper, I needed this to be able to compile with native-image, because I didn't find any way to properly configure it. If you can help me with this, I would like to make it work without this flag (maybe with `@AutomaticFeature` that detects SimpleFlatMapper classes?).

Maybe we can move this discussion to https://github.com/micronaut-graal-tests/micronaut-jooq-graal issue tracker and if you would like to help me with guiding, I will try to improve the first point and we can collaborate on the second one.

**Comment by morki** [comment]
@ilopmar Can I contribute your idea of JPA annotation generation with link to https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/  to the `micronaut-sql` documentation JOOQ section?

**Comment by morki** [comment]
I splitted remaining problems into issues in https://github.com/micronaut-graal-tests/micronaut-jooq-graal

**Comment by ilopmar** [comment]
> Hi @ilopmar, you are my hero, really! :) The simple trick with `@Entity` annotation is excelent, I will try it right now!
> 

Actually it was Graeme's idea to take a look at https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/. I only enabled the flag and tested it worked.
BTW, I've also updated the docs: https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#_graalvm_native_image

P.S: Yes, let's continue the discussion in the other repo :)

**Pull request closed without merging**
